'use client';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {useState,useTransition,useEffect,useRef} from 'react';
import {mutate} from '@/lib/actions/work-order-actions';
import type {Snapshot,Property,Asset,WorkOrder} from '@/lib/data/types';
import {hours,date,weekStart} from '@/lib/utils/time';
const sections=[['properties','Properties','building'],['assets','Assets','asset'],['work-orders','Work Orders','orders'],['weekly-status','Weekly Status','chart']];
const types=['HVAC','lift','fire_alarm','electrical_panel','water_system'];
const label=(s:string)=>s.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
function Icon({name,size=20}:{name:string;size?:number}){const paths:Record<string,string>={building:'M4 21V3h12v18M8 7h4M8 11h4M8 15h4M16 9h4v12M2 21h20',asset:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M5 19l2-2M17 7l2-2',orders:'M8 4H5v17h14V4h-3M8 2h8v4H8zM8 11h8M8 15h5',chart:'M4 20V4M4 20h17M9 16v-5M14 16V7M19 16v-8',plus:'M12 5v14M5 12h14',arrow:'M5 12h14M14 7l5 5-5 5',search:'M10 3a7 7 0 1 0 0 14 7 7 0 0 0 0-14M15 15l6 6',check:'M5 12l4 4L19 6',clock:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18M12 7v5l3 2',close:'M6 6l12 12M6 18L18 6'};return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.asset}/></svg>;}
function Badge({value}:{value:string}){return <span className={`badge ${value}`}>{value==='wip'?'In progress':label(value)}</span>;}
function Field({name,title,value,required=false,type='text',min}:{name:string;title:string;value?:string|number|null;required?:boolean;type?:string;min?:number}){return <label className="field"><span>{title}{required?' *':''}</span><input name={name} defaultValue={value??''} required={required} type={type} min={min} maxLength={4000}/></label>;}
export default function MaintenanceApp({section,data,loadError}:{section:string;data:Snapshot;loadError?:string}){
 const router=useRouter();const [pending,startTransition]=useTransition();const [search,setSearch]=useState('');const [property,setProperty]=useState('all');const [status,setStatus]=useState('all');const [week,setWeek]=useState(0);const [modal,setModal]=useState<{kind:string;record?:Property|Asset|WorkOrder}|null>(null);const [selected,setSelected]=useState<string|null>(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [formProperty,setFormProperty]=useState('');const dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(modal||selected){dialogRef.current?.showModal();}else dialogRef.current?.close();},[modal,selected]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(t);},[notice]);
 const open=(kind:string,record?:Property|Asset|WorkOrder)=>{setError('');setSelected(null);setFormProperty(record&&'property_id'in record?record.property_id:data.properties[0]?.id||'');setModal({kind,record});};
 const close=()=>{if(pending)return;setModal(null);setSelected(null);setError('');};
 const run=(kind:string,f:FormData,keep=false)=>{setError('');startTransition(async()=>{try{const result=await mutate(kind,f);if(!result.ok){setError(result.error||'Could not save. Check connection.');return;}setNotice(kind.startsWith('delete')?'Record deleted.':'Changes saved.');if(!keep){setModal(null);setSelected(null);}router.refresh();}catch{setError('Could not save. Check connection and try again.');}});};
 const matches=(text:string)=>text.toLowerCase().includes(search.toLowerCase());
 const propertyName=(id:string)=>data.properties.find(p=>p.id===id)?.name||'Property';
 const assetName=(id:string|null)=>data.assets.find(a=>a.id===id)?.name||'General issue';
 const orders=data.orders.filter(o=>(property==='all'||o.property_id===property)&&(status==='all'||o.status===status)&&matches(o.title+' '+o.description+' '+o.assigned_to_name+' '+propertyName(o.property_id)));
 const current=data.orders.find(o=>o.id===selected);
 const active=data.orders.filter(o=>o.status!=='resolved');const resolved=data.orders.filter(o=>o.status==='resolved');const times=resolved.map(o=>o.resolution_time_hours).filter((x):x is number=>x!==null);
 const start=weekStart(week),end=new Date(start.getTime()+7*86400000);
 const weekly=data.orders.filter(o=>o.status==='resolved'?!!o.resolved_at&&new Date(o.resolved_at)>=start&&new Date(o.resolved_at)<end:new Date(o.created_at)<end);
 const heading=sections.find(s=>s[0]===section)?.[1]||'Properties';
 const subtitle:Record<string,string>={properties:'Every building. One clear picture.',assets:'Know your machinery, down to the last detail.','work-orders':'From first report to a job well done.','weekly-status':'Your portfolio’s maintenance pulse.'};
 const orderCard=(o:WorkOrder)=><button className="order-card" key={o.id} onClick={()=>{setError('');setModal(null);setSelected(o.id);}}><div className="order-card-top"><span className="record-id">WO-{o.id.slice(0,6).toUpperCase()}</span><Badge value={o.priority}/></div><h3>{o.title}</h3><p>{propertyName(o.property_id)} · {assetName(o.asset_id)}</p><div className="order-card-bottom"><Badge value={o.status}/><span>{o.status==='resolved'?`Resolved in ${hours(o.resolution_time_hours)}`:o.assigned_to_name||'Unassigned'} <Icon name="arrow" size={16}/></span></div></button>;
 return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-icon"><Icon name="building" size={24}/></span><span>building<span className="brand-sub">MAINTENANCE WORKSPACE</span></span></Link><div className="nav-label">WORKSPACE</div><nav aria-label="Main navigation">{sections.map(([key,title,icon])=><Link key={key} href={key==='properties'?'/':`/${key}`} className={section===key?'nav-item active':'nav-item'} aria-current={section===key?'page':undefined}><Icon name={icon}/><span>{title}</span>{key==='work-orders'&&active.length>0&&<small>{active.length}</small>}</Link>)}</nav><div className="sidebar-note"><span className="live-dot"/> Demo workspace<p>A shared space to explore your maintenance workflow.</p></div><div className="sidebar-footer"><span className="avatar">BM</span><div>Building manager<small>Operations team</small></div></div></aside>
 <div className="main-shell"><header className="topbar"><span className="breadcrumb">Workspace <span>/</span> {heading}</span><span className="demo-pill"><span className="live-dot"/> Live demo</span></header><main><div className="page-heading"><div><div className="eyebrow">BUILDING OPERATIONS</div><h1>{heading}</h1><p>{subtitle[section]}</p></div>{section!=='weekly-status'&&<button className="button primary" onClick={()=>open(section==='properties'?'property':section==='assets'?'asset':'order')} disabled={!!loadError||((section==='assets'||section==='work-orders')&&!data.properties.length)}><Icon name="plus"/>{section==='properties'?'Add Property':section==='assets'?'Add Asset':'New Issue'}</button>}</div>
 {notice&&<div className="toast" role="status"><Icon name="check"/>{notice}</div>}{loadError?<div className="error-panel" role="alert"><h2>Unable to load records</h2><p>{loadError}</p><button className="button primary" onClick={()=>router.refresh()}>Retry</button></div>:<>
 <div className="stats"><div className="stat"><span>{section==='assets'?'Registered assets':'Properties managed'}</span><strong>{section==='assets'?data.assets.length:data.properties.length}</strong><small>{section==='assets'?'Across your portfolio':'Your building portfolio'}</small></div><div className="stat"><span>Open work orders</span><strong>{active.length}<i className="stat-dot amber"/></strong><small>{active.filter(o=>o.status==='pending').length} awaiting action</small></div><div className="stat"><span>In progress</span><strong>{active.filter(o=>o.status==='wip').length}<i className="stat-dot blue"/></strong><small>With your technicians</small></div><div className="stat"><span>Average resolution</span><strong>{times.length?hours(times.reduce((a,b)=>a+b,0)/times.length):'—'}</strong><small>Across {resolved.length} resolved issues</small></div></div>
 <div className="section-toolbar"><div className="section-title"><h2>{section==='properties'?'Your properties':section==='assets'?'Asset registry':section==='work-orders'?'All work orders':'Weekly overview'}</h2><span className="count-pill">{section==='properties'?data.properties.length:section==='assets'?data.assets.length:section==='work-orders'?data.orders.length:weekly.length}</span></div>{section!=='weekly-status'&&<div className="search"><Icon name="search" size={18}/><input aria-label="Search records" placeholder={section==='properties'?'Search properties…':section==='assets'?'Search assets…':'Search work orders…'} value={search} onChange={e=>setSearch(e.target.value)}/></div>}</div>
 {section!=='properties'&&<div className="filters"><label>Property <select value={property} onChange={e=>setProperty(e.target.value)}><option value="all">All properties</option>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>{section==='work-orders'&&<div className="status-tabs">{['all','pending','wip','resolved'].map(s=><button key={s} className={status===s?'selected':''} onClick={()=>setStatus(s)}>{s==='all'?'All statuses':s==='wip'?'In progress':label(s)}</button>)}</div>}{section==='weekly-status'&&<div className="week-picker"><button className="button quiet" aria-label="Previous week" onClick={()=>setWeek(week-1)}>←</button><span>{date(start.toISOString())} – {date(new Date(end.getTime()-1).toISOString())}</span><button className="button quiet" aria-label="Next week" onClick={()=>setWeek(week+1)} disabled={week===0}>→</button>{week!==0&&<button className="button quiet" onClick={()=>setWeek(0)}>This week</button>}</div>}</div>}
 {section==='properties'&&<div className="registry-grid">{data.properties.filter(p=>matches(p.name+' '+p.address)).map((p,i)=><article className="property-card" key={p.id}><div className={`property-art art-${i%3}`}><div className="building-shape"><span/><span/><span/><span/><span/><span/><span/><span/><span/></div><span className="art-caption">PROPERTY {String(i+1).padStart(2,'0')}</span><span className="art-icon"><Icon name="building" size={28}/></span></div><div className="property-body"><h3>{p.name}</h3><p>{p.address||'No address added'}</p><div className="property-meta"><span><b>{p.floors}</b> floors</span><span><b>{p.units}</b> units</span><span><b>{data.assets.filter(a=>a.property_id===p.id).length}</b> assets</span></div><div className="property-status"><span><i className="stat-dot amber"/>{active.filter(o=>o.property_id===p.id).length} open issues</span><button className="text-button" onClick={()=>open('property',p)}>View & edit <Icon name="arrow" size={16}/></button></div></div></article>)}</div>}
 {section==='assets'&&<div className="registry-grid">{data.assets.filter(a=>(property==='all'||a.property_id===property)&&matches(a.name+' '+a.type+' '+a.model_number+' '+a.serial_number)).map(a=><article className="asset-card" key={a.id}><div className="asset-top"><span className="asset-symbol"><Icon name="asset" size={26}/></span><span className="type-label">{label(a.type)}</span></div><h3>{a.name}</h3><p>{propertyName(a.property_id)}</p><dl className="asset-details"><div><dt>Location</dt><dd>{a.location_floor?`Floor ${a.location_floor}`:'—'}{a.location_unit?` · ${a.location_unit}`:''}</dd></div><div><dt>Model</dt><dd>{a.model_number||'—'}</dd></div><div><dt>Serial</dt><dd>{a.serial_number||'—'}</dd></div><div><dt>Purchased</dt><dd>{date(a.purchase_date)}</dd></div><div><dt>Installed</dt><dd>{date(a.install_date)}</dd></div><div><dt>Warranty</dt><dd className={a.warranty_expiry&&new Date(a.warranty_expiry)<new Date()?'expired':''}>{date(a.warranty_expiry)}{a.warranty_expiry&&new Date(a.warranty_expiry)<new Date()?' · Expired':''}</dd></div></dl><button className="text-button" onClick={()=>open('asset',a)}>View & edit asset <Icon name="arrow" size={16}/></button></article>)}</div>}
 {section==='work-orders'&&<div className="order-grid">{orders.map(orderCard)}</div>}
 {section==='weekly-status'&&<><p className="week-note">Open issues carried forward · Resolved issues completed during the selected week · Times in MYT</p>{data.properties.filter(p=>property==='all'||p.id===property).map(p=>{const rows=weekly.filter(o=>o.property_id===p.id);return <section className="weekly-property" key={p.id}><div className="weekly-heading"><span className="asset-symbol"><Icon name="building"/></span><div><h3>{p.name}</h3><p>{rows.length} work orders in this view</p></div></div><div className="weekly-columns">{['pending','wip','resolved'].map(s=><div className={`weekly-bucket ${s}`} key={s}><h4><Badge value={s}/><span>{rows.filter(o=>o.status===s).length}</span></h4>{rows.filter(o=>o.status===s).map(orderCard)}{!rows.some(o=>o.status===s)&&<p className="bucket-empty">{s==='resolved'?'No resolutions this week.':'All clear here.'}</p>}</div>)}</div></section>;})}</>}
 {((section==='properties'&&!data.properties.filter(p=>matches(p.name+' '+p.address)).length)||(section==='assets'&&!data.assets.filter(a=>(property==='all'||a.property_id===property)&&matches(a.name+' '+a.type+' '+a.model_number+' '+a.serial_number)).length)||(section==='work-orders'&&!orders.length)||(section==='weekly-status'&&!weekly.length))&&<div className="empty-state"><Icon name={section==='properties'?'building':'orders'} size={36}/><h3>{search||property!=='all'||status!=='all'?'No matching records':section==='properties'?'No properties yet':section==='assets'?'No assets yet':section==='weekly-status'?'No activity this week':'No work orders yet'}</h3><p>{search||property!=='all'||status!=='all'?'Try another search or filter.':section==='properties'?'Add your first building to get started.':section==='assets'?'Register your first piece of machinery.':section==='weekly-status'?'Report an issue to start tracking progress.':'Create the first issue.'}</p>{!data.properties.length&&section!=='properties'&&<Link className="button primary" href="/">Add your first property</Link>}</div>}
 </>}<footer className="page-footer"><span>BUILDING MMS</span><span>Made for the people who keep buildings running.</span></footer></main></div>
 <dialog ref={dialogRef} onCancel={close} className="record-dialog"><div className="dialog-header"><div><div className="eyebrow">{current?'WORK ORDER DETAILS':'MAINTENANCE RECORD'}</div><h2>{current?current.title:modal?.record?'Edit '+label(modal.kind):modal?.kind==='order'?'Report a new issue':'Add '+label(modal?.kind||'record')}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={close} disabled={pending}><Icon name="close"/></button></div>{error&&<div role="alert" className="form-error">{error}</div>}
 {current&&<div className="order-detail"><div className="detail-badges"><Badge value={current.status}/><Badge value={current.priority}/><span>Score {current.priority_score} · Rule engine</span></div><p className="detail-description">{current.description||'No additional description.'}</p><dl className="detail-grid"><div><dt>Property</dt><dd>{propertyName(current.property_id)}</dd></div><div><dt>Asset</dt><dd>{assetName(current.asset_id)}</dd></div><div><dt>Reported by</dt><dd>{current.reported_by_name||'—'}</dd></div><div><dt>Reported</dt><dd>{date(current.created_at)}</dd></div><div><dt>First response</dt><dd>{hours(current.response_time_hours)}</dd></div><div><dt>Resolution time</dt><dd>{hours(current.resolution_time_hours)}</dd></div></dl>{current.status!=='resolved'&&<form onSubmit={e=>{e.preventDefault();run('assign',new FormData(e.currentTarget),true);}} className="assignment-form"><input type="hidden" name="id" value={current.id}/><Field name="assigned_to_name" title="Assigned technician" value={current.assigned_to_name} required/><button className="button secondary" disabled={pending}>{pending?'Saving…':'Save assignment'}</button></form>}<div className="detail-actions">{current.status==='pending'&&<form onSubmit={e=>{e.preventDefault();run('start',new FormData(e.currentTarget),true);}}><input type="hidden" name="id" value={current.id}/><button className="button primary" disabled={pending||!current.assigned_to_name}>{pending?'Saving…':'Start Work'}<Icon name="arrow" size={18}/></button></form>}{current.status==='wip'&&<form onSubmit={e=>{e.preventDefault();run('resolve',new FormData(e.currentTarget),true);}}><input type="hidden" name="id" value={current.id}/><label className="confirm-label"><input type="checkbox" name="confirmed" value="yes" required/> I confirm the issue is resolved.</label><button className="button primary" disabled={pending}>{pending?'Saving…':'Resolve Issue'}<Icon name="check" size={18}/></button></form>}{current.status==='resolved'&&<div className="resolved-summary"><Icon name="check"/> Resolved {date(current.resolved_at)} · {hours(current.resolution_time_hours)}</div>}<button className="text-button" disabled={pending} onClick={()=>open('order',current)}>Edit issue</button></div><h3 className="activity-title">Activity history</h3><ol className="activity-list">{data.logs.filter(l=>l.entity_id===current.id).map(l=><li key={l.id}><span className="activity-dot"/><div><b>{label(l.action.replace('work_order.',''))}</b><p>{l.detail}</p><small>{l.actor_name} · {date(l.created_at)}</small></div></li>)}</ol><form className="danger-zone" onSubmit={e=>{e.preventDefault();run('delete-order',new FormData(e.currentTarget));}}><input type="hidden" name="id" value={current.id}/><label className="confirm-label"><input type="checkbox" required name="confirmed" value="yes"/> Confirm permanent deletion of this issue.</label><button className="button danger" disabled={pending}>Delete work order</button></form></div>}
 {modal&&<form onSubmit={e=>{e.preventDefault();run(modal.kind,new FormData(e.currentTarget));}} className="record-form"><input type="hidden" name="id" value={modal.record?.id||''}/>{modal.kind==='property'&&<><Field name="name" title="Property name" value={(modal.record as Property)?.name} required/><Field name="address" title="Address" value={(modal.record as Property)?.address}/><div className="form-row"><Field name="floors" title="Floors" type="number" min={1} value={(modal.record as Property)?.floors||1} required/><Field name="units" title="Units" type="number" min={1} value={(modal.record as Property)?.units||1} required/></div></>}
 {(modal.kind==='asset'||modal.kind==='order')&&<label className="field"><span>Property *</span><select name="property_id" required value={formProperty} onChange={e=>setFormProperty(e.target.value)}>{data.properties.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>}
 {modal.kind==='asset'&&<><Field name="name" title="Asset name" value={(modal.record as Asset)?.name} required/><label className="field"><span>Type *</span><select name="type" defaultValue={(modal.record as Asset)?.type||'HVAC'}>{types.map(t=><option key={t} value={t}>{label(t)}</option>)}</select></label><div className="form-row"><Field name="model_number" title="Model number" value={(modal.record as Asset)?.model_number}/><Field name="serial_number" title="Serial number" value={(modal.record as Asset)?.serial_number}/></div><div className="form-row"><Field name="location_floor" title="Floor" value={(modal.record as Asset)?.location_floor}/><Field name="location_unit" title="Unit / location" value={(modal.record as Asset)?.location_unit}/></div><div className="form-row"><Field name="purchase_date" title="Purchase date" type="date" value={(modal.record as Asset)?.purchase_date}/><Field name="install_date" title="Installation date" type="date" value={(modal.record as Asset)?.install_date}/></div><Field name="warranty_expiry" title="Warranty expiry" type="date" value={(modal.record as Asset)?.warranty_expiry}/></>}
 {modal.kind==='order'&&<><Field name="title" title="Issue title" value={(modal.record as WorkOrder)?.title} required/><label className="field"><span>Description</span><textarea name="description" rows={4} maxLength={4000} defaultValue={(modal.record as WorkOrder)?.description||''} placeholder="What happened? Include the floor, unit and symptoms."/></label><label className="field"><span>Linked asset</span><select name="asset_id" key={formProperty} defaultValue={(modal.record as WorkOrder)?.property_id===formProperty?(modal.record as WorkOrder)?.asset_id||'':''}><option value="">General issue / no asset</option>{data.assets.filter(a=>a.property_id===formProperty).map(a=><option key={a.id} value={a.id}>{a.name} · {label(a.type)}</option>)}</select></label><Field name="reported_by_name" title="Reported by" value={(modal.record as WorkOrder)?.reported_by_name} required/><p className="form-help">Priority is calculated automatically from the asset, symptoms and warranty.</p></>}
 <div className="form-actions"><button type="button" className="button quiet" onClick={close} disabled={pending}>Cancel</button><button className="button primary" disabled={pending}>{pending?'Saving…':modal.record?'Save Changes':modal.kind==='order'?'Create Issue':'Save '+label(modal.kind)}</button></div></form>}
 {modal?.record&&modal.kind!=='order'&&<form className="danger-zone" onSubmit={e=>{e.preventDefault();run('delete-'+modal.kind,new FormData(e.currentTarget));}}><input type="hidden" name="id" value={modal.record.id}/><label className="confirm-label"><input type="checkbox" name="confirmed" value="yes" required/> Confirm permanent deletion. Linked records must be removed first.</label><button className="button danger" disabled={pending}>Delete {modal.kind}</button></form>}
 </dialog></div>;
}